# Generated by Django 4.0.2 on 2022-03-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knowledge',
            old_name='regist_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='knowledge',
            old_name='update_date',
            new_name='updated_at',
        ),
    ]
