# Generated by Django 4.0.2 on 2022-03-17 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_rename_regist_date_knowledge_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knowledge',
            old_name='created_at',
            new_name='regist_date',
        ),
        migrations.RenameField(
            model_name='knowledge',
            old_name='updated_at',
            new_name='update_date',
        ),
    ]
