# Generated by Django 4.0.2 on 2022-03-17 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0003_rename_created_at_knowledge_regist_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knowledge',
            old_name='contributor',
            new_name='created_by',
        ),
    ]
