# Generated by Django 4.0.2 on 2022-03-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0004_rename_contributor_knowledge_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='regist_date',
            field=models.DateTimeField(verbose_name='投稿日'),
        ),
    ]
